//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure_MDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public int idLibrosUnidades { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal Precio { get; set; }
        public string NombreLCliente { get; set; }
    
        public virtual LibrosUnidade LibrosUnidade { get; set; }
        public virtual Venta Ventas1 { get; set; }
        public virtual Venta Venta1 { get; set; }
    }
}
